# Generated by Django 4.0.1 on 2022-01-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('review', models.TextField()),
                ('date_published', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=512)),
                ('rating', models.IntegerField()),
                ('cover_art', models.CharField(max_length=512)),
                ('author', models.ManyToManyField(related_name='books', to='booklist.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booklist.category')),
                ('genres', models.ManyToManyField(related_name='books', to='booklist.Genre')),
                ('tags', models.ManyToManyField(related_name='books', to='booklist.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(related_name='authors', to='booklist.Tag'),
        ),
    ]
