# Generated by Django 4.0.1 on 2022-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_alter_book_review_alter_book_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_art',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
