# Generated by Django 4.0.2 on 2022-03-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0009_remove_book_url_alter_bookurl_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booklist.book'),
        ),
    ]
